const publisherEvents = {
  LOAD_DATA: 'LOAD_DATA',
  SEARCH_MODEL: 'SEARCH_MODEL',
  FILTERED_DATA: 'FILTERED_DATA',
  CAR_DETAILS: 'CAR_DETAILS',
  SHOW_FILTER: 'SHOW_FILTER',
  LOGO_SHOWCARS: 'LOGO_SHOWCARS',
  SHOW_PARTNERS: 'SHOW_PARTNERS',
  SHOW_CONTACTS: 'SHOW_CONTACTS',
  RESET_DATA: 'RESET_DATA',
};

export default publisherEvents;